### ISSUE TITLE
Software does not work as expected

### ISSUE THREAD

**Issue by ziorufus** [racai-ai/pyeurovoc#3] opened 2022-09-08 13:01 UTC
Hi! We tried to use the pyeurovoc model using the example code included in the README, but the results seem almost random (and completely different from the ones expected and listed in the documentation).

Source code:
```
from pyeurovoc import EuroVocBERT

model = EuroVocBERT(lang="en")
prediction = model("Commission Decision on a modification of the system of aid applied in Italy in respect of shipbuilding")

print(prediction)
```

We just added a `print(prediction)` at the end of the code, and we downgraded `scikit-learn` to version 0.24.1 as required by a warning message.

```
~/eurovoc$ python test.py 
Configuration found in the .cache directory '/home/alessio/.cache/pyeurovoc/model_en/config.json'. Loading...
Model found in the .cache directory '/home/alessio/.cache/pyeurovoc/model_en/pytorch_model.bin'. Loading...
Label encoder 'mlb_encoder_en.pickle' found in the .cache directory at '/home/alessio/.cache/pyeurovoc'. Loading...
{'2734': 0.9550160765647888, '3367': 0.9118708372116089, '5545': 0.9061976075172424,
  '20': 0.9018628597259521, '3169': 0.8950178027153015, '75': 0.8861560225486755}
```

We verified that 2734, 3367, etc. are completely unrelated w.r.t. the input text.

Interesting fact: we tried this code on two different machines (one with CPU, the other one with GPU), and we obtained the same exact results.
In the CPU machine, we also added the `device="cpu"` in the model constructor `EuroVocBERT`.

Moreover, if we change the text a bit (by removing "a" in "on a modification") we get quite different results:
```
{'3367': 0.9468291401863098, '2734': 0.9428318738937378, '797': 0.9132468700408936,
  '491': 0.8979585766792297, '5946': 0.8878598213195801, '161': 0.8829310536384583}
```

Machine 1 (CPU): Intel(R) Xeon(R) CPU E3-1245 with Ubuntu 20.04.4 LTS, Python 3.8.10
Machine 2 (GPU): Intel(R) Xeon(R) CPU E5-1650 with Ubuntu 20.04.3 LTS (GPU NVIDIA TITAN Xp), Python 3.8.5

Are we doing anything wrong?

**Comment by avramandrei** [comment] 2022-09-09 06:54
Hi,

You are not doing anything wrong in particular. I have tested your example, and the predictions indeed are odd.

I believe that this is a data shift and model robustness problem. We trained our models exclusively on OPOCE and ACQUIS datasets that are available here: https://joint-research-centre.ec.europa.eu/language-technology-resources/jrc-eurovoc-indexer-jex_en (in `workspace/cf` directory)

If you take a look at the samples they are a little bit different than your input text:

```
DECISION creating the "Official Journal of the European Communities" THE COUNCIL OF THE EUROPEAN ECONOMIC COMMUNITY, Having regard to Article 191 of the Treaty establishing the European Economic Community; Having regard to the proposals from the President of the European Parliament and the Presidents of the High Authority, the Commission of the European Economic Community and the Commission of the European Atomic Energy Community; Whereas the European Economic Community, the European Coal and Steel Community and the European Atomic Energy Community should have a joint official journal; HAS DECIDED: to create, as the official journal of the Community within the meaning of Article 191 of the Treaty establishing the European Economic Community, the Official Journal of the European Communities.
```

I am not sure if this can help you, but maybe you can rephrase your sentences in this way.

**Comment by ziorufus** [comment] 2022-09-09 09:49
Hi @avramandrei, thank you for your quick answer.

We would like to use your trained models for our downstream tasks, but we are now wondering about the very reliability of the models themselves. It sounds hard to give credence to the ‘data shift’ hypothesis, as the models were only created/published last year and we are using the same (pretty simple) sentence from the README. For the same reasons, ‘robustness’ should not be called into question. Any trained model, even a neural one, is expected to be deterministic (same input -> same output). We are just wondering which model did ever produce the (expected) results you show in the README, as we would really like to use such a model. As a side remark, these quick (and absolutely inconclusive) trials seem also to challenge the reproducibility of the results showed in the paper.

The sentence you suggested in your answer produced following results:
```
1605 aubergine 0.93
5050 budget 0.91
5383 technological change 0.9
862 EU aid 0.89
5751 combined nomenclature 0.87
5640 operation of the institutions 0.87
```

Thank you for pointing us to the original datasets. Nevertheless, we would be very grateful if you would keep us informed of any further developments or solutions to the problem.

**Comment by avramandrei** [comment] 2022-09-09 10:55
Oh, I was not even aware that the example you gave was the one we put in the README. Thanks for pointing this out!

If these results are inconsistent, then it is a fault on our side (and a quite serious one). I will take a deeper look by the end of this week into the code/models and I will come with an update.

**Comment by avramandrei** [comment] 2022-09-15 06:56
Sorry for the late response. After some debugging, I believe that the problem comes from the fact that the authors of the JurBERT (the English model used for fine-tuning) have changed the tokenizer configuration: https://huggingface.co/nlpaueb/legal-bert-base-uncased/tree/main (you can see that the `tokenizer_config.json` file has been modified 5 months ago).

Currently, this library is using that file for loading the tokenizer and I am trying to figure out what might be different from the version we used in the past (I wish I had saved everything on our repositories...). I will come with new updates in the incoming days.

**Comment by mrovera** [comment] 2022-09-15 14:00
[follows from @ziorufus answer, we are working together]
Hi,
thank you for reaching out. Well, if it can be of any help for you, we have been trying also models in other languages (notably in Italian) and the problem arises the same way. This seems to suggest that the issue affects some part of the pipeline which is shared over all languages, thus not language-specific.
We kindly ask you to get in touch as soon as you have some news, and whatever the outcome of your debugging, as the availability (or non-availability) of working models is critical to our work plan. Thank you very much!

**Comment by avramandrei** [comment] 2022-09-16 10:38
I believe I have identified the problem. It looks like we did not correctly migrated the models when we wanted to make them compatible with the new interface of the Transformers library.

To use the old code, please refactor the code to the following commit: `00a4c3b76b0ff34bb3e3030ab15b19885a5f85ee`

Also, please not that to use that version of the code, you need the `transformers<4.11.x`. I recommend `transformers==4.10.3`

I have tested the code with that version and everything looks to be working fine. I get the predictions found in the readme.

Please let me know if this also works for you as well. I will convert the code back to that commit and will try to make another migration at the end of this month.

**Comment by avramandrei** [comment] 2022-09-16 10:52
P.S. I did the reverted the code to that commit. You should be able to update your code with:

```
pip install -U pyeurovoc
```

**Comment by mrovera** [comment] 2022-09-16 11:34
Cool! After updating the code I too was able to reproduce the original results. I would wait a moment and do some experiments before closing the issue. In the meantime, thanks a lot!

**Comment by avramandrei** [comment] 2022-09-16 12:41
You're welcome! Sure, please do!. Let me know if everything is ok.

**Closed** 2022-10-22 07:04 UTC
